apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scoring-job.fullname" . }}-rules
  labels:
    app.kubernetes.io/name: {{ include "scoring-job.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  rules.yaml: |
{{ .Files.Get "rules.yaml" | indent 4 }}
